"""
ResQVision — Incident Report Agent
=====================================
Generates structured emergency reports (text + optional PDF).
"""

import os
from datetime import datetime

try:
    from fpdf import FPDF
    PDF_AVAILABLE = True
except ImportError:
    PDF_AVAILABLE = False


class ReportAgent:
    """Generate structured incident reports for command centres."""

    # Mock GPS coordinates (simulated field locations)
    MOCK_LOCATIONS = [
        ("28.6139° N, 77.2090° E", "New Delhi Sector 7 — Flood Zone Alpha"),
        ("19.0760° N, 72.8777° E", "Mumbai Western Express — Collapse Site B"),
        ("13.0827° N, 80.2707° E", "Chennai Coastal Belt — Surge Area C"),
        ("22.5726° N, 88.3639° E", "Kolkata East Bank — Flood Zone Delta"),
    ]

    def __init__(self, report_dir: str = "logs"):
        self.report_dir = report_dir
        os.makedirs(report_dir, exist_ok=True)
        self._report_counter = 0

    def generate(
        self,
        survivor_count: int,
        risk_level: str,
        risk_score: int,
        strategy: dict,
        resources: dict,
        confidence_score: float = 0.0,
        flood_risk: bool = False,
        micro_motion_confidence: float = 0.0,
        breathing_confidence: float = 0.0,
    ) -> str:
        """
        Generate a formatted incident report.

        Returns
        -------
        str
            Human-readable report text.
        """
        self._report_counter += 1
        loc_idx = self._report_counter % len(self.MOCK_LOCATIONS)
        gps, location_name = self.MOCK_LOCATIONS[loc_idx]
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        report_id = f"RQV-{datetime.now().strftime('%Y%m%d')}-{self._report_counter:04d}"

        lines = [
            "╔══════════════════════════════════════════════════════════════╗",
            "║          RESQVISION — EMERGENCY INCIDENT REPORT             ║",
            "╚══════════════════════════════════════════════════════════════╝",
            "",
            f"  Report ID      : {report_id}",
            f"  Timestamp      : {timestamp}",
            f"  GPS Coordinates: {gps}",
            f"  Location       : {location_name}",
            "",
            "─── SITUATION ASSESSMENT ──────────────────────────────────────",
            "",
            f"  Survivors Detected     : {survivor_count}",
            f"  Detection Confidence   : {confidence_score:.1%}",
            f"  Risk Level             : {risk_level}",
            f"  Risk Score             : {risk_score}/100",
            f"  Flood Risk             : {'YES ⚠' if flood_risk else 'NO'}",
            f"  Micro-Motion Confidence: {micro_motion_confidence:.1%}",
            f"  Breathing Confidence   : {breathing_confidence:.1%}",
            "",
            "─── RECOMMENDED STRATEGY ─────────────────────────────────────",
            "",
            f"  Strategy : {strategy.get('strategy', 'N/A')}",
            f"  Priority : {strategy.get('priority', 'N/A')}",
            "",
            "  Equipment Required:",
        ]
        for item in strategy.get("equipment", []):
            lines.append(f"    • {item}")
        lines.append("")
        lines.append("  Recommended Actions:")
        for action in strategy.get("actions", []):
            lines.append(f"    ➤ {action}")

        lines += [
            "",
            "─── RESOURCE ALLOCATION ───────────────────────────────────────",
            "",
            f"  Ambulances      : {resources.get('ambulances', 0)}",
            f"  Rescue Teams    : {resources.get('rescue_teams', 0)}",
            f"  Medical Units   : {resources.get('medical_units', 0)}",
            f"  Helicopters     : {resources.get('helicopters', 0)}",
            f"  Supply Trucks   : {resources.get('supply_trucks', 0)}",
            f"  Total Personnel : {resources.get('total_personnel', 0)}",
            "",
            "═══════════════════════════════════════════════════════════════",
            f"  Generated by ResQVision v1.0 — {timestamp}",
            "═══════════════════════════════════════════════════════════════",
        ]

        report_text = "\n".join(lines)

        # Save text report
        report_path = os.path.join(self.report_dir, f"report_{report_id}.txt")
        with open(report_path, "w", encoding="utf-8") as f:
            f.write(report_text)

        return report_text

    def export_pdf(self, report_text: str, filename: str | None = None) -> str | None:
        """
        Export report as PDF. Returns file path or None if fpdf2 not installed.
        """
        if not PDF_AVAILABLE:
            print("[WARN] fpdf2 not installed — PDF export skipped.")
            return None

        if filename is None:
            filename = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"

        pdf_path = os.path.join(self.report_dir, filename)
        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("Courier", size=9)

        for line in report_text.split("\n"):
            pdf.cell(0, 5, txt=line, ln=True)

        pdf.output(pdf_path)
        return pdf_path
